### ISSUE TITLE
Delete uploaded files when you delete an import job

### ISSUE THREAD

**Issue by tinmarr** [auto-mat/django-import-export-celery#104]
Would be good to delete the uploaded files once the job is deleted. Currently, this needs to be done manually (or automatically every x days using another celery task).

**Comment by timthelion** [comment]
Wait, once the job is run or the job is deleted?

**Comment by tinmarr** [comment]
Once it is deleted

**Comment by timthelion** [comment]
https://stackoverflow.com/questions/16041232/django-delete-filefield#16041527

We can probably add a post_delete safely here. I've got nothing against a PR that does so...
