### ISSUE TITLE
django.core.exceptions.FieldDoesNotExist: ExportJob has no field named 'job_status_info'

### ISSUE THREAD

**Issue by JindalAnkush** [auto-mat/django-import-export-celery#11]
During file export, I am getting below error.
ExportJob has no field named 'job_status_info'

/lib/python3.6/site-packages/Django-2.2.3-py3.6.egg/django/db/models/options.py", line 567, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: ExportJob has no field named 'job_status_info'

During handling of the above exception, another exception occurred:

**Comment by timthelion** [comment]
I cannot reproduce this.
