### ISSUE TITLE
Release v 1.7?

### ISSUE THREAD

**Issue by heso** [auto-mat/django-import-export-celery#121]
Maybe its time to release v.1.7 from master?
It's difficult to use the current 1.6 version, in particular due to https://github.com/auto-mat/django-import-export-celery/issues/112

**Comment by PetrDlouhy** [comment]
@timthelion Will you release the changes? Or if you give me rights to PyPI, I could make the release myself.

**Comment by timthelion** [comment]
Does it not automatically publish to pypi if you make a github release? https://github.com/auto-mat/django-import-export-celery/blob/master/.github/workflows/publish-to-live-pypi.yml

**Comment by PetrDlouhy** [comment]
Thanks, I didn't know how this works. Now I hope I do.

But there is still an error:
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         User 'timthelion' does not have a verified primary email address.      
         Please add a verified primary email before attempting to upload to     
         PyPI. See https://pypi.org/help/#verified-email for more information.  
```
https://github.com/auto-mat/django-import-export-celery/actions/runs/9170809174/job/25213785443

**Comment by PetrDlouhy** [comment]
@timthelion I think you have to verify your e-mail address on PyPI (through verification e-mail) in order to fix the releases with GitHub.

https://github.com/auto-mat/django-import-export-celery/actions/runs/9253021714/job/25451863455

**Comment by timthelion** [comment]
@PetrDlouhy should be fixed.

**Comment by PetrDlouhy** [comment]
@timthelion Thank you very much. 1.7.1 is now released.
