### ISSUE TITLE
Unable to export large amount of  data

### ISSUE THREAD

**Issue by JindalAnkush** [auto-mat/django-import-export-celery#13]
Hi, I am not able to export a large amount of data(10 millions of rows).
the system gets a timeout issue and takes a massive amount of memory.
JSON list of pks to export:  Instead of ids, can we save the query.

**Comment by timthelion** [comment]
You can send a PR :)

**Comment by JindalAnkush** [comment]
sorry, I can not give you PR. 
when i am going to export 10millions of rows. create_export_job_action function get time out issue.
and queryset field in  import_export_celery_exportjob was unable to save that amount of data.
