### ISSUE TITLE
No module named 'project'

### ISSUE THREAD

**Issue by ethanjahn** [auto-mat/django-import-export-celery#15]
Hi Team,

This library looks great, I would love to use it for my project! Unfortunately, when I add 'import_export_celery' to my INSTALLED_APPS, I get a ModuleNotFound error due to the expectation that the folder containing celery.py is called 'project' (from `__init__.py`).

Renaming this folder would require a huge amount of effort. Any way that we could use a setting to control the top-level directory name?

Also, in case I'm interpreting wrong the stack trace is below. I am running Django 3.0 with Gunicorn and Python 3.8. The project is containerized with two seperate Celery worker containers.

Stack Trace:
```backend              | [2020-02-13 21:02:11 +0000] [12] [ERROR] Exception in worker process
backend              | Traceback (most recent call last):
backend              |   File "/opt/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
backend              |     worker.init_process()
backend              |   File "/opt/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 129, in init_process
backend              |     self.load_wsgi()
backend              |   File "/opt/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
backend              |     self.wsgi = self.app.wsgi()
backend              |   File "/opt/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
backend              |     self.callable = self.load()
backend              |   File "/opt/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
backend              |     return self.load_wsgiapp()
backend              |   File "/opt/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
backend              |     return util.import_app(self.app_uri)
backend              |   File "/opt/venv/lib/python3.8/site-packages/gunicorn/util.py", line 350, in import_app
backend              |     __import__(module)
backend              |   File "/home/default/delta_mvp/wsgi.py", line 11, in <module>
backend              |     application = get_wsgi_application()
backend              |   File "/opt/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
backend              |     django.setup(set_prefix=False)
backend              |   File "/opt/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
backend              |     apps.populate(settings.INSTALLED_APPS)
backend              |   File "/opt/venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
backend              |     app_config = AppConfig.create(entry)
backend              |   File "/opt/venv/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
backend              |     module = import_module(entry)
backend              |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
backend              |     return _bootstrap._gcd_import(name[level:], package, level)
backend              |   File "/opt/venv/lib/python3.8/site-packages/import_export_celery/__init__.py", line 1, in <module>
backend              |     from project.celery import app as celery_app
backend              | ModuleNotFoundError: No module named 'project'

**Comment by timthelion** [comment]
Hi, this is probably pretty easy to change. If you are able to modify your environment, then git cloning the repo and doing `pip install -e /path/to/git/repo` will let you change the source. I suspect the change will be four lines long and will look like:

````
- from project.celery import app as celery_app
+from django.conf import settings
+import importlib
+celery_module = settings.get('CELERY_INIT_MODULE', 'project.celery')
+celery_app = importlib.import_module(celery_module).app
````

But you'll have to test for yourself.

**Comment by ethanjahn** [comment]
Happy to test it and make it work - would your team be interested in a PR? 

Would love to have it in pypi to make it easier to add to container based projects

**Comment by timthelion** [comment]
I don't think it should interfere with anything, so I'm fine with a PR. Make sure you document it somehow.

**Comment by gotedkid195** [comment]
Sorry @timthelion , I got the same error when installing this package.
    app_config = AppConfig.create(entry)
  File "/home/canhnguyen/.local/share/virtualenvs/iteslateq-platform-RP_V8dSf/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/canhnguyen/.local/share/virtualenvs/iteslateq-platform-RP_V8dSf/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/canhnguyen/.local/share/virtualenvs/iteslateq-platform-RP_V8dSf/lib/python3.7/site-packages/import_export_celery/__init__.py", line 1, in <module>
    from project.celery import app as celery_app
ModuleNotFoundError: No module named 'project'

1. I don't know where to put your code ?
"
- from project.celery import app as celery_app
+ from django.conf import settings
+ import importlib
+ celery_module = settings.get('CELERY_INIT_MODULE', 'project.celery')
+ celery_app = importlib.import_module(celery_module).app
"

2, With your instructions not specific about:
IMPORT_EXPORT_CELERY_MODELS = {
    "Winner": {'app_label': 'winners', 'model_name': 'Winner'}
}
model_name: where ?

**Comment by timthelion** [comment]
@gotedkid195 [app_label](https://docs.djangoproject.com/en/3.0/ref/contrib/contenttypes/#django.contrib.contenttypes.models.ContentType.app_label) is a specific django term. In your case I think it would be "app_parameter" and the module would be "ValueLog".

**Comment by timthelion** [comment]
This should be fixed now https://github.com/auto-mat/django-import-export-celery/pull/18
