### ISSUE TITLE
Can you remove the line exist in import_export_celery\__init__.py

### ISSUE THREAD

**Issue by Milstein** [auto-mat/django-import-export-celery#21]
When I do makemigration it shows: 
```
"import_export_celery\__init__.py", line 1, in <module>
    from project.celery import app as celery_app
```

Just need to remove this line completely from that __init__.py file.

**Comment by timthelion** [comment]
You cannot simply remove that line, it is required for tasks to be registered successfully. You'll need to update to version 0.1.2 and set the 'IMPORT_EXPORT_CELERY_INIT_MODULE' in your settings.py file.
