### ISSUE TITLE
How do you load a resource in IMPORT_EXPORT_CELERY_MODELS?

### ISSUE THREAD

**Issue by charleshan** [auto-mat/django-import-export-celery#22]
```
IMPORT_EXPORT_CELERY_MODELS = {
    "Winner": {'app_label': 'winners', 'model_name': 'Winner'}
}
```
"The available parameters are app_label, model_name, and resource. **'resource' should be a function which returns a django-import-export Resource.**"

This is what the documentation says but we can't add a resource before loading the app. Also, adding a string doesn't work.

**Comment by timthelion** [comment]
That's why it's a function 😉. You can import within functions. The function will be called after the app is loaded.

**Comment by charleshan** [comment]
Oh... I miss that small bit of detail. We should add this to the doc for people like me 😅

Thanks for thel help!

```
def resource():
    from myapp.models import WinnerResource
    return WinnerResource


IMPORT_EXPORT_CELERY_MODELS = {
    "Winner": {
        'app_label': 'winners',
        'model_name': 'Winner',
        'resource': resource,
    }
}
```
