### ISSUE TITLE
Job finished but no objects created

### ISSUE THREAD

**Issue by charleshan** [auto-mat/django-import-export-celery#24]
`Job status info: 5/5 Import job finished`

I see thousands of rows in the import summary with the `change_type` `new` but nothing was added to the database.

**Comment by timthelion** [comment]
Did you do step 6? The first run is a dry run. Obviously, themessaging should be improved.

**Comment by timthelion** [comment]
Would you please create a PR updating the message? https://github.com/auto-mat/django-import-export-celery/blob/a6febc4c0ce34aecbcf58feb0abc65a0224b8c9b/import_export_celery/tasks.py#L174

**Comment by timthelion** [comment]
And it doesn't say [Dry run] in the status?

**Comment by charleshan** [comment]
Yes, that's why include the full message. This is after "Perform import." I think it says [Dry run] when it is a dry run, as you mentioned.

It says this underneath.
`Has the import been completed? If so when?: June 23, 2020, 11:19 a.m.`

**Comment by charleshan** [comment]
That fixed it. I guess this is related to the other issue I submitted https://github.com/auto-mat/django-import-export-celery/issues/23

We need to handle `SoftTimeLimitExceeded` and `TimeLimitExceeded` (hard time limit). Or at least display the exception errors in the job info.
