### ISSUE TITLE
Support arbitrary celery variable name

### ISSUE THREAD

**Issue by zdytch** [auto-mat/django-import-export-celery#27]
Won't work, when using celery variable other than 'app'

`AttributeError: module 'projectname.celery' has no attribute 'app'`

**Comment by timthelion** [comment]
Can you explain under what circumstances you end up using an non-standard celery variable?

**Comment by zdytch** [comment]
As far as I understand there is no "standard Celery variable". "app" is just an example from Celery documentation, and you are free to write you own.

In my case that happened because of code styling requirements for project. There could be other circumstances, I guess.

The point of this issue is not to rely on particular implementation, as there is no convention or documented requirement to name Celery variable strictly "app".

**Comment by timthelion** [comment]
I'm actually not now 100% sure if the stuff in __init__.py is even needed. When looking at the source code for "django-celery-email" for example, no such code is there. https://github.com/pmclanahan/django-celery-email/blob/master/djcelery_email/__init__.py

And they manage to register and run celery tasks successfully.

Would you mind trying to delete the contents of our __init__.py and seeing if it helps?

**Comment by zdytch** [comment]
I confirm that the error disappears after cleaning `import_export_celery/__init__.py`.
However the stability effect is unknown.

PS. The funny part is, the init file itself contains `celery_app = importlib.import_module(celery_module).app`.
And `celery_app` is the exact Celery variable used on my project.

**Comment by timthelion** [comment]
If it works without those lines in __init__.py I would just remove them. Can you make a PR? I'm quite sure that I only added them because I was following some sort of tutorial ;)

**Comment by zdytch** [comment]
#28
