### ISSUE TITLE
schedule to Import data 

### ISSUE THREAD

**Issue by Bill188** [auto-mat/django-import-export-celery#3]
Could we have the function to schedule to Import data to Django? For example, import data and update report for every 30 minutes? 
Thanks,

**Comment by timthelion** [comment]
I don't understand what you mean. Is the data to be imported changing over time?

5. září 2019 4:10:19 SELČ, Bill188 <notifications@github.com> napsal:

**Comment by Bill188** [comment]
Thank you very much for your reply. Yes, I have a csv file on my local drive (or could be on a URL) which is exported from a database and it refreshes every 30 minutes. I need to import this csv file to Django model as a table format and also refresh it for every 30 minutes. I see django-import-export-celery can set to import the csv file at a specific date/time. Would you be able to get an option to import the file every 30 minutes, 1 hour, 1 day etc.?  Thanks,

**Comment by timthelion** [comment]
Yes, you can do this.

1. Create a PR which adds a boolean `dry_run_before_importing` field (which defaults to `True`) to the ImportJob object https://github.com/auto-mat/django-import-export-celery/blob/master/import_export_celery/models/importjob.py and then passes the value of that field to the `dry_run` parameter in the post_save hook here https://github.com/auto-mat/django-import-export-celery/blob/d30a4e3d1ea4ebd46a2ee2ff66e7374103d4e0ee/import_export_celery/models/importjob.py#L89

2. Install django celery beat: https://django-celery-beat.readthedocs.io/en/latest/

3. create a tasks.py file where you register a celery task which creates an ImportJob object with the newly updated file and `dry_run_before_importing` set to `False`.

4. Configure celery beat to run your task every 30 minutes.

Sorry, I do not have the time to help you beyond this.

**Comment by Bill188** [comment]
Much appreciated Tim. I'll work on this.
