### ISSUE TITLE
Migrations pending

### ISSUE THREAD

**Issue by r9software** [auto-mat/django-import-export-celery#30]
Installed aps
django-import-export-celery==1.1.3
issue:
E           AssertionError: Your models have changes that are not yet reflected in a migration. You should add them now. Relevant app(s): dict_keys(['import_export_celery'])

It looks like there are pending migrations on the latest release, and then local migrations are failing on tests, I can't run makemigrations to do a work around because I don't have permission on the folder where the code of the library is located.

**Comment by timthelion** [comment]
Does anything actually not work? We use this in production, and I haven't noticed any migration problems. Is it possible that there is some trivial non-relevant change to the model, like a label that hasn't been baked into a migration yet?

**Comment by r9software** [comment]
@timthelion I basically followed the docs, and I got this error on the library, when I try to run the migration this is the error I get
 /opt/api/venv-3.6.8/lib/python3.6/site-packages/import_export_celery/migrations/0007_auto_20201125_1730.py
    - Alter field model on importjob
Traceback (most recent call last):
  File "./manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/api/venv-3.6.8/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/api/venv-3.6.8/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/api/venv-3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/api/venv-3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/api/venv-3.6.8/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 193, in handle
    self.write_migration_files(changes)
  File "/opt/api/venv-3.6.8/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 232, in write_migration_files
    with io.open(writer.path, "w", encoding='utf-8') as fh:
PermissionError: [Errno 13] Permission denied: '/opt/api/venv-3.6.8/lib/python3.6/site-packages/import_export_celery/migrations/0007_auto_20201125_1730.py'

**Comment by r9software** [comment]
I see what is the issue... 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery', '0006_auto_20191125_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='model',
            field=models.CharField(choices=[('Services', 'Services'), ('ServiceCategory', 'ServiceCategory')], max_length=160, verbose_name='Name of model to import to'),
        ),
    ]

**Comment by r9software** [comment]
Solution is to copy all migrations  and use migration-modules
https://docs.djangoproject.com/en/1.11/ref/settings/#migration-modules
https://stackoverflow.com/questions/27444525/how-can-i-tell-django-1-7-to-put-migration-into-specific-folder

**Comment by samupl** [comment]
This solution doesn't seem to work anymore, at least not out of the box.

In current version (1.6), on a fresh project, django tries to generate migrations that seem to change the storage class and the choices:

```
> python manage.py makemigrations
Migrations for 'import_export_celery':
  /usr/local/lib/python3.11/site-packages/import_export_celery/migrations/0010_alter_exportjob_file_alter_importjob_change_summary_and_more.py
    - Alter field file on exportjob
    - Alter field change_summary on importjob
    - Alter field file on importjob
  
> cat /usr/local/lib/python3.11/site-packages/import_export_celery/migrations/0010_alter_exportjob_file_alter_importjob_change_summary_and_more.py
# Generated by Django 4.2.1 on 2023-09-23 14:01

import config.custom_storages
from django.db import migrations
import import_export_celery.fields


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery', '0009_alter_exportjob_options_alter_importjob_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='file',
            field=import_export_celery.fields.ImportExportFileField(max_length=255, storage=config.custom_storages.TempFileStorage(), upload_to='django-import-export-celery-export-jobs', verbose_name='exported file'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='change_summary',
            field=import_export_celery.fields.ImportExportFileField(blank=True, null=True, storage=config.custom_storages.TempFileStorage(), upload_to='django-import-export-celery-import-change-summaries', verbose_name='Summary of changes made by this import'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='file',
            field=import_export_celery.fields.ImportExportFileField(max_length=255, storage=config.custom_storages.TempFileStorage(), upload_to='django-import-export-celery-import-jobs', verbose_name='File to be imported'),
        ),
    ]
```

I followed your suggestion and moved all migrations from the package to `common/migrations/` - which is an empty module, has no prior migrations:

```
>ls common/migrations/
__init__.py
> cp -rf /usr/local/lib/python3.11/site-packages/import_export_celery/migrations/* common/migrations/
> rm -rf common/migrations/__pycache__/
```

And I tried running `makemigrations`, this is what I get:

```
> python manage.py makemigrations
System check identified some issues:

WARNINGS:
dictionaries.Keyword.name: (fields.W905) django.contrib.postgres.fields.CICharField is deprecated. Support for it (except in historical migrations) will be removed in Django 5.1.
	HINT: Use CharField(db_collation="…") with a case-insensitive non-deterministic collation instead.
dictionaries.RequestKeyword.name: (fields.W905) django.contrib.postgres.fields.CICharField is deprecated. Support for it (except in historical migrations) will be removed in Django 5.1.
	HINT: Use CharField(db_collation="…") with a case-insensitive non-deterministic collation instead.
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0001_initial, 0002_auto_20190923_1132, 0003_exportjob, 0004_exportjob_email_on_completion, 0005_exportjob_site_of_origin, 0006_auto_20191125_1236, 0007_auto_20210210_1831, 0008_alter_exportjob_id_alter_importjob_id, 0009_alter_exportjob_options_alter_importjob_options_and_more, 0010_alter_exportjob_file_alter_importjob_change_summary_and_more in common).
To fix them run 'python manage.py makemigrations --merge'
```

Creating a merge migration also doesn't seem to work:

```
> python manage.py makemigrations --merge
System check identified some issues:

WARNINGS:
dictionaries.Keyword.name: (fields.W905) django.contrib.postgres.fields.CICharField is deprecated. Support for it (except in historical migrations) will be removed in Django 5.1.
	HINT: Use CharField(db_collation="…") with a case-insensitive non-deterministic collation instead.
dictionaries.RequestKeyword.name: (fields.W905) django.contrib.postgres.fields.CICharField is deprecated. Support for it (except in historical migrations) will be removed in Django 5.1.
	HINT: Use CharField(db_collation="…") with a case-insensitive non-deterministic collation instead.
Traceback (most recent call last):
  File "/opt/mba/django/src/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/makemigrations.py", line 194, in handle
    return self.handle_merge(loader, conflicts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/makemigrations.py", line 439, in handle_merge
    raise ValueError(
ValueError: Could not find common ancestor of ['0001_initial', '0002_auto_20190923_1132', '0003_exportjob', '0004_exportjob_email_on_completion', '0005_exportjob_site_of_origin', '0006_auto_20191125_1236', '0007_auto_20210210_1831', '0008_alter_exportjob_id_alter_importjob_id', '0009_alter_exportjob_options_alter_importjob_options_and_more', '0010_alter_exportjob_file_alter_importjob_change_summary_and_more']
```

Ultimatelly I think this issue is still valid - even if everything works without creating a new migration, a library making the project complain about missing migrations doesn't seem right.

**Comment by samupl** [comment]
As a temporary workaround, I set:

```python
MIGRATION_MODULES = {
    'import_export_celery': None,
}
```

Which tells django that the `import_export_celery` does not have migrations. But this has some disadvantages, mainly:

* needs to be removed for the first deployment (migration run),
* will ignore any migrations for updates of the package, unless commented out for migrations again
