### ISSUE TITLE
 [Dry run] Error reading file

### ISSUE THREAD

**Issue by pierreclaverkoko** [auto-mat/django-import-export-celery#31]
After import job succeeded, I just have an error 

`Error reading file: [Errno 2] No such file or directory: 'project/django-import-export-celery-import-jobs/file.csv'`

The file is well saved in ImportJob instance. This means in 'project/media/django-import-export-celery-import-jobs/file.csv' and the import celery doesn't find it (from MEDIA_ROOT).

**Comment by timthelion** [comment]
Where do you see this error? In the console? Or displayed somehow in an error message on the web?

**Comment by Dufran** [comment]
I received the same error in my case this was because celery beat was running as separate service in docker, and files was pulled from the image of Django service, not mounted. My solution was to make a volume that accessible to celery and Django services

**Comment by timthelion** [comment]
I believe that this only happens if your django MEDIA files configuration is not compatible with celery. This cannot be fixed in this library and must be addressed by users individually.

**Comment by smac89** [comment]
For people who use docker containers, and run `django` and celery seperately:

After you setup your media file paths as shown [here](https://docs.djangoproject.com/en/3.2/howto/static-files/#serving-uploaded-files-in-development), you need to create a shared volume that points to the same path as `MEDIA_ROOT` on both containers.
