### ISSUE TITLE
Celery 5 support

### ISSUE THREAD

**Issue by matthewelwell** [auto-mat/django-import-export-celery#38]
Hi there,

I've noticed that this package doesn't support celery 5 since the `celery.task` module has been deprecated which is used in the `tasks` module here.

I am happy to take a look to see if there is an option to fix this in a PR but I thought I'd raise it here to see if you have any thoughts.

Thanks,
Matt

**Comment by Goldziher** [comment]
So I forked this repo - and it seems that this has been resolved.

**Comment by timthelion** [comment]
Like in your fork? Is there a PR?

**Comment by timthelion** [comment]
I just released 1.1.4, I think this should be fixed?
