### ISSUE TITLE
update project setup to make collaboration easier

### ISSUE THREAD

**Issue by Goldziher** [auto-mat/django-import-export-celery#40]
Hi There,

So i forked this repo to make some updates and I encountered some difficulties with the setup- I would like to suggest the following updates:

1. migrate to using poetry instead of setup.py, and then add the dependencies and dev dependencies at the root level. 
2. migrate to using github actions, works with poetry: https://github.com/snok/install-poetry
3. add pre-commit
4. add contribution guidelines
5. add unit tests - currently there is really nothing

I would be glad to help with some of these if you are interested.

**Comment by timthelion** [comment]
Would `1` maybe fix https://github.com/auto-mat/django-import-export-celery/issues/20 ?

**Comment by timthelion** [comment]
`5` the only "test" is this https://github.com/auto-mat/django-import-export-celery/blob/67b9fa699d22f9ed4e23f5a355a5058dd0327ea1/example/winners/tests/test_admin.py#L9

**Comment by timthelion** [comment]
What would `2` do?

**Comment by timthelion** [comment]
You did see that we have travis https://travis-ci.com/github/auto-mat/django-import-export-celery/jobs/506689595 didn't you?

**Comment by Goldziher** [comment]
So,

1.poetry is very nice and simple to use.
2. See this for pre-commit: https://link.medium.com/HVz8neQ5pgb
3. Travis changed their policies,  and github actions are great. 
4. Zero coverage

**Comment by timthelion** [comment]
How did travis change their policies?

**Comment by Goldziher** [comment]
Well, they changed their policy regard open source etc. Google it.

Anyhow, I ended up writing custom logic instead of using this library.
