### ISSUE TITLE
Missing middleware

### ISSUE THREAD

**Issue by Goldziher** [auto-mat/django-import-export-celery#41]
Hi, the docs need to be updated with an explanation that the AuthorMiddleware is required, I'm getting this error:

Error "author.middlewares.AuthorDefaultBackendMiddleware" is not found in MIDDLEWARE_CLASSES nor MIDDLEWARE. It is required to use AuthorDefaultBackend

Also, since this is apparently a part of this package as well - maybe it should be clarified that the author middleware is a requirement here.

**Comment by cfdbwrbq** [comment]
its impossible to use "author.middlewares.AuthorDefaultBackendMiddleware" in project where field "author" of some model type is CharField?

TypeError: Tried to update field app.SomeModel.author with a model instance, <SimpleLazyObject: <User: admin>>. Use a value compatible with CharField.

**Comment by timthelion** [comment]
@cfdbwrbq I just read the code for `django-author` and there is this really stupid code that adds a universal pre-save hook, rather than adding the hook only for models with the `@withauthor` decorator.

https://github.com/lambdalisue/django-author/blob/aa296bf50d67800c26fd4e9a62af910824f0d460/author/recivers.py#L56

That alone is enough to show that `django-author` isn't the best code and that we should move away from it entirely. Until then, setting `AUTHOR_MODELS` to `['import_export_celery.ExportJob', 'import_export_celery.ImportJob']` in your `settings.py` file should clear things up.

**Comment by aparakian** [comment]
Sadly the solution `AUTHOR_MODELS = ['import_export_celery.exportjob', 'import_export_celery.importjob']` creates this error :

```
File "/import_export_celery/models/__init__.py", line 5, in <module>
    from import_export_celery.models.exportjob import ExportJob
  File "/import_export_celery/models/exportjob.py", line 21, in <module>
    from author.decorators import with_author
  File "/author/__init__.py", line 121, in <module>
    recivers.register()
  File "/author/recivers.py", line 61, in register
    pre_save.connect(pre_save_callback, sender=ct.model_class())
  File "/django/contrib/contenttypes/models.py", line 163, in model_class
    return apps.get_model(self.app_label, self.model)
  File "/django/apps/registry.py", line 193, in get_model
    self.check_models_ready()
  File "/django/apps/registry.py", line 132, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by timthelion** [comment]
Have you tried putting `import_export_celery` before `author` in 
`INSTALLED_APPS`?

**Comment by aparakian** [comment]
Before or after, at the end or the beginning of the `INSTALLED_APPS` it's the same so far. 
After removing all the `__init__` imports on my fork, it did the job but now having other issues so rolling back. 
I'm just writing this in case somebody has the same issue.

**Comment by timthelion** [comment]
I think that the only real solution is to get rid of the authors dependency. I think that a simple pull request to delete it would suffice, it's more of a nice to have feature. If anyone really wants to see who did the export, we can add a field (author), with a ForeignKey relationship to the user who called the admin action to create the export.

**Comment by aparakian** [comment]
I agree, I'll see if I have time in the future. 
Though, I do think it's a good feature to send the completion email to the one who created the export, it would be nice to continue saving the author in some way.

**Comment by AhmedAlZabidi** [comment]
This issue can be closed by merge this [pull request](https://github.com/auto-mat/django-import-export-celery/pull/50)
