### ISSUE TITLE
Add changelist template 

### ISSUE THREAD

**Issue by Goldziher** [auto-mat/django-import-export-celery#42]
Currently the way import/export works is with an action, from the action dropdown. 

The problem here is that sometimes you want to have custom logic that is not based on selecting elements from a model list. In my case I need an export action that exports hundreds of thousand of rows into csv - and the user needs to make a selection in a dropdown but not pass a list of pks. Instead I am overriding the get_queryset method of the resource in question.

**Comment by timthelion** [comment]
I think this is a dup of https://github.com/auto-mat/django-import-export-celery/issues/37#issuecomment-811294500
