### ISSUE TITLE
How to show progress of import  in dry_run=True?

### ISSUE THREAD

**Issue by everestkid** [auto-mat/django-import-export-celery#44]
`
  if row_number % 100 == 0 or row_number == 1:                    
change_job_status(                        import_job,                        "import",                        "3/5 Importing row %s/%s" % (row_number, len(dataset)),                        dry_run,                    )`

https://github.com/auto-mat/django-import-export-celery/blob/67b9fa699d22f9ed4e23f5a355a5058dd0327ea1/import_export_celery/tasks.py#L80
This does not work for dry run. I think it is due to atomic transaction so the database is not updated when doing a dry run . It work only when dry_run = False and using_transactions = False

**Comment by timthelion** [comment]
I'm pretty sure this depends on how your cache is setup. If your cache is set up so that it is shared between celery and the django instance than this will work (for example, you are using redis), but if you are using caches that are local to the instances, than there isn't really a way to make this work IMO.

**Comment by everestkid** [comment]
@timthelion  Sorry I didn't understand it well. Please guide me in the right direction. Can you provide a link to some resources? My goal is to show progress when importing ( atomic transactions).

**Comment by timthelion** [comment]
Look in your setting.py file at the CACHES setting. Is it memcached to a local socket? Is that socket shared between celery and your webserver? Are celery and your webserver running on different machines or in different containers? If so you'll need to set up a shared cache using redis https://realpython.com/caching-in-django-with-redis/

**Comment by everestkid** [comment]
thank you very much
