### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by aabanaag** [auto-mat/django-import-export-celery#52]
I integrated this on one of the projects I'm working on, seems fine I noticed the migration issue but even if I do the makemigrations the migration file doesn't apply properly.

<img width="1112" alt="Screen Shot 2021-11-22 at 9 43 06 PM" src="https://user-images.githubusercontent.com/2245822/142872566-24c6f7fc-079a-4c4e-9623-b0aa5758d375.png">

The generated migration is under this path `/usr/local/lib/python3.8/site-packages/import_export_celery/migrations/0008_auto_20211122_1340.py` but trying to navigate to this direct nothing is generated...

I also know that a similar issue was created but I can't seem to find proper documentation about migration modules. Any ideas?

**Comment by marksweb** [comment]
This is caused by the choices loading settings respective to the project the app is implemented in;

```
    model = models.CharField(
        verbose_name=_("Name of model to import to"),
        max_length=160,
        choices=[
            (x, x) for x in getattr(settings, "IMPORT_EXPORT_CELERY_MODELS", {}).keys()
        ],
    )
```

The solution here would be to define choices as an empty list and lazy load them.

I've got a fix. Will raise PR later on.
