### ISSUE TITLE
Release new version 1.1.5 to PyPi

### ISSUE THREAD

**Issue by LizardBob** [auto-mat/django-import-export-celery#54]
Please release new version 1.1.5 to PyPI in case current release has bug which had been already fixed in current code version. 
![2cbad854-eb35-4021-bea2-ba7709d3e9fb](https://user-images.githubusercontent.com/37070885/150805239-f1d1b758-de8f-4ac4-b1ad-1bd3258e9753.png)

**Comment by timthelion** [comment]
https://pypi.org/project/django-import-export-celery/1.1.6/

**Comment by iflare3g** [comment]
@timthelion thanks so much!
