### ISSUE TITLE
Renaming the app and hide import

### ISSUE THREAD

**Issue by GergelyKovach** [auto-mat/django-import-export-celery#57]
Hello!

I think the AppConfig setup is missing, because there is no defined app name.
![image](https://user-images.githubusercontent.com/91737686/157668893-b8ad5571-9d50-48a4-8556-cee9f8a4589f.png)

So how to rename the app for the backend users?
And how to remove the import admin page in the menu?

**Comment by marksweb** [comment]
This will be resolved by #60
