### ISSUE TITLE
How to provide customised querysets for the export job

### ISSUE THREAD

**Issue by xalien10** [auto-mat/django-import-export-celery#68]
Currently, I'm trying to export a model which might contain a lot of annotated data from different models related to the user model. 
But when I export I got only the Model's data and annotated data is missing. But this can be found while using export functionality of `django-import-export` export action.
I was wondering if there is any way to customise the queryset for the targeted export model with celery export
@timthelion

**Comment by timthelion** [comment]
This isn't currently supported. I don't know how you are doing this in import export celery. Perhaps you could attach a new method to the resource that you are using and then use that method here: Line 103 in file import_export_celery/models/exportjob.py at auto-mat/django-import-export-celery - https://github.com/auto-mat/django-import-export-celery/blob/master/import_export_celery/models/exportjob.py#L103

Like if you added an `anotate_queryset` method to your resource and then added a line there that would **try** calling that method...

**Comment by xalien10** [comment]
For instance, I've the `User` model and `UserResource` which is a `ModelResource` from `django-import-export` package.

I want the queryset Like below:
```
def get_queryset(self):
        pks = json.loads(self.queryset)
        return User.objects.annotate(device_type=Subquery(
                    FCMDevice.objects.filter(user=OuterRef("pk")).values(
                        "type")[:1]
                )).filter(pk__in=pks)
```

instead of 
```
def get_queryset(self):
        pks = json.loads(self.queryset)
        return self.get_content_type().model_class().objects.filter(pk__in=pks)
```

**Comment by timthelion** [comment]
Yes, I understood you. Feel free to make a PR, though I can't guarantee I'll merge it on the first version.. BTW, you can do this with a custom manager without modifying this library https://docs.djangoproject.com/en/4.0/topics/db/managers/ but for performance reasons I don't recomend it.

**Comment by xalien10** [comment]
@timthelion are you going to delay the release for this issue?

**Comment by timthelion** [comment]
Fixed https://github.com/auto-mat/django-import-export-celery/pull/69
