### ISSUE TITLE
Unable to see add button under export screen

### ISSUE THREAD

**Issue by JindalAnkush** [auto-mat/django-import-export-celery#7]
Hi,  I am not able to see the add button in the django-export screen. Do i need to give any extra permission?
after modifying "has_add_permission" function(return true) . i was able to see the add button. but still would not see module information.

**Comment by timthelion** [comment]
That's because you add an export job by using the "Export with celery" admin action. Adding exports is by hand is explicitly dissabled because we use hidden fields to configure ContentTypes.

**Comment by JindalAnkush** [comment]
Hi @timthelion , I am new in this field. can you please help me or give me an example

**Comment by timthelion** [comment]
Did you read the instructions? https://github.com/auto-mat/django-import-export-celery#setting-up-exports are they unclear?

**Comment by JindalAnkush** [comment]
@timthelion , Thanks timethelion. now i am able to export data. but still, I have an issue. I am not able to export a mail to multiple team member

**Comment by timthelion** [comment]
What do you mean by "abstract models"?

Sending mail to multiple members is not supported. The user who started the export is notified.

What issues are you having defining "export_resource_classes"?

**Comment by JindalAnkush** [comment]
abstract model, where abstract = True
in the abstract model, we were getting some circular reference issue. now it is resolved by dynamic function.
But when we are trying to export more 2.4 million records, the system did not get any response to the open "ExportJob object" screen. but its work fine for few records
