### ISSUE TITLE
Document custom queryset code

### ISSUE THREAD

**Issue by timthelion** [auto-mat/django-import-export-celery#70]
https://github.com/auto-mat/django-import-export-celery/pull/69 is not documented

**Comment by xalien10** [comment]
I'm adding it in the documentation as soon as possible

**Comment by xalien10** [comment]
Added the documentation. Please take a look if something needs to be changed or not. @timthelion

**Comment by xalien10** [comment]
Thank you so much for your quick and kind response 👍
