### ISSUE TITLE
Latest change (ugettext_lazy) not published to pypi

### ISSUE THREAD

**Issue by edxavier** [auto-mat/django-import-export-celery#74]
i have compared the code from exportjob.py in github agaist the pypi and this file is not updated in pipy

**Comment by timthelion** [comment]
Yeah, 4.0 support was added in May, the last release was in April. Should be in version 1.3 which I just uploaded. Should be live in a few minutes. BTW, I noticed that you went to the effort to add a new release to pypi to add this support. That's not strictly necessary for pulling in a dependency. Python dependencies can be pulled directly from git, here is an example: https://github.com/auto-mat/klub/blob/ca58572905d79afde723e70e681d9e1107dc0aab/requirements.txt#L40

If you are using pipenv or poetry, the syntax is a bit different, for example with poetry that looks like: https://github.com/auto-mat/do-prace-na-kole/blob/c07e24dda4ac07d24422488bb3e01dfbc3aecef2/monorepo/docker-base-image/pyproject.toml#L13

use google to find the pipenv syntax.
