### ISSUE TITLE
Change the email sent to user to another language or text.

### ISSUE THREAD

**Issue by jonathanprieto99** [auto-mat/django-import-export-celery#83]
Is it possible to change the email values based on some variables or based on the language used in the app?

**Comment by timthelion** [comment]
Line 238 in file import_export_celery/tasks.py at auto-mat/django-import-export-celery - https://github.com/auto-mat/django-import-export-celery/blob/master/import_export_celery/tasks.py#L238 hmm, doesn't seem so without changing thisline to load from a template. If you change this line to build the email from,a template https://github.com/auto-mat/do-prace-na-kole/blob/e46e0aa8e3f0e7baa2fd9cd4b4a03518856bb808/apps/dpnk/email.py#L242 then you can override the template in your code. If you make a clean PR Iwould merge it.
