### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by timthelion** [auto-mat/django-import-export-celery#86]
Hello,
it seems this project is getting lasting attention. It deserves more maintainers. If you'd like to step up to the plate, just comment below. :)
Thanks

**Comment by Jaspreet-singh-1032** [comment]
Hi @timthelion, I would like to help in maintaining this project.

**Comment by timthelion** [comment]
Yes, that would be an excellent place to start. Thank you! Looking forward to seeing the PR.

**Comment by timthelion** [comment]
I'd like to welcome @xalien10 and @Jaspreet-singh-1032 to the team as maintainers. :)
