### ISSUE TITLE
IMPORT_DRY_RUN_FIRST_TIME feature is not released, while being in a master

### ISSUE THREAD

**Issue by a4tarasiuk** [auto-mat/django-import-export-celery#96]
Please, make a patch release with this change - https://github.com/auto-mat/django-import-export-celery/commit/1ecabe2e4a26001376ec2bbf3b9c31152253daaf

The change was merged to master a month ago.
The feature is really needed.

**Comment by timthelion** [comment]
should be here https://pypi.org/project/django-import-export-celery/1.4/

**Comment by a4tarasiuk** [comment]
> should be here https://pypi.org/project/django-import-export-celery/1.4/

Yeah, it just is not described in the releases section, so when first come to repository, it shows 1.3 as the latest.
